export enum DistrictItaly {
    Abruzzo = 1,
    Basilicata = 2,
    Calabria = 3,
    Campania = 4,
    EmiliaRomagna = 5,
    FriuliVeneziaGiulia = 6,
    Lazio = 7,
    Liguria = 8,
    Lombardia = 9,
    Marche = 10,
    Molise = 11,
    Piemonte = 12,
    Puglia = 13,
    Sardegna = 14,
    Sicilia = 15,
    Toscana = 16,
    TrentinoAltoAdigeSudtirol = 17,
    Umbria = 18,
    ValleDAosta = 19,
    Veneto = 20
}